### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by riseshia** [riseshia/fubura#1]
- [x] apply/plan `--config` option
- [x] jsonnet evaluation
- [x] export feature
- [x] plan impl
- [x] support delete flag
- [x] ~schedule tag support~
- [x] sfn tag support
- [x] gen ops list from diff
- [x] apply impl
- [x] bulk support import
- [x] bulk support plan
- [x] bulk support apply
- [x] --target support
- [x] example config
- [x] pretty log
- [x] add required iam permission list (doc)
- [x] release
- [x] --output json support
- [x] check readme
- [x] better error handling than panic
- [x] add to tap https://github.com/riseshia/homebrew-x/pull/5
- [x] install action
